name: p36
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.6.1=py36_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - astor=0.7.1=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - boto3=1.9.35=py36_0
  - botocore=1.12.35=py36_0
  - bzip2=1.0.6=h1de35cc_5
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2018.11.29=py36_0
  - cffi=1.11.5=py36h6174b99_1
  - cryptography=2.4.1=py36ha12b0ac_1
  - cycler=0.10.0=py36hfc81398_0
  - decorator=4.3.0=py36_0
  - docutils=0.14=py36hbfde631_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.0=py36_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - graphite2=1.3.12=h2098e52_2
  - grpcio=1.16.1=py36h044775b_1
  - h5py=2.8.0=py36h878fce3_3
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - icu=58.2=h4b95b61_1
  - idna=2.7=py36_0
  - intel-openmp=2019.1=144
  - ipython=7.2.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jasper=2.0.14=h636a363_1
  - jedi=0.13.1=py36_0
  - jmespath=0.9.3=py36_0
  - jpeg=9b=he5867d9_2
  - keras=2.2.4=0
  - keras-applications=1.0.6=py36_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.35=ha441bb4_0
  - libprotobuf=3.6.1=hd9629dc_0
  - libtiff=4.0.9=hcb84e12_2
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.8=hab757c2_1
  - markdown=3.0.1=py36_0
  - matplotlib=3.0.2=py36h54f8f79_0
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py36h27c97d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.15.4=py36hacdab7b_0
  - numpy-base=1.15.4=py36h6575580_0
  - olefile=0.46=py36_0
  - openssl=1.1.1a=h1de35cc_0
  - pandas=0.23.4=py36h6440ff4_0
  - parso=0.3.1=py36_0
  - patsy=0.5.1=py36_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.3.0=py36hb68e598_0
  - pip=18.1=py36_0
  - pixman=0.34.0=hca0a616_3
  - prompt_toolkit=2.0.7=py36_0
  - protobuf=3.6.1=py36h0a44026_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36h7c891bd_1
  - pycparser=2.19=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.3.0=py36_0
  - pysocks=1.6.8=py36_0
  - python=3.6.7=haf84260_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.7=py36_0
  - pyyaml=3.13=py36h1de35cc_0
  - readline=7.0=h1de35cc_5
  - s3transfer=0.1.13=py36_0
  - scikit-learn=0.20.1=py36h27c97d8_0
  - scipy=1.1.0=py36h1410ff5_2
  - seaborn=0.9.0=py36_0
  - setuptools=40.6.2=py36_0
  - six=1.12.0=py36_0
  - sqlite=3.25.3=ha441bb4_0
  - statsmodels=0.9.0=py36h1d22016_0
  - tensorboard=1.12.0=py36hdc36e2c_0
  - tensorflow=1.12.0=mkl_py36h2b2bbaf_0
  - tensorflow-base=1.12.0=mkl_py36h70e0e9a_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - urllib3=1.24.1=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cloudpickle==0.6.1
    - dask==1.0.0
    - fcsparser==0.2.0
    - keras-vis==0.4.1
    - networkx==2.2
    - pydot==1.4.1
    - pywavelets==1.0.1
    - scikit-image==0.14.1
    - toml==0.10.0
    - toolz==0.9.0

